### ISSUE TITLE
Replace Preview Picture

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-landing#14]
![preview picture dexpay](https://user-images.githubusercontent.com/10923247/55410199-be0a9a80-5563-11e9-8787-fced5870481a.png)

**Comment by gagansaini1212** [comment]
Replace with?

**Comment by dimarconicola** [comment]
> Replace with?

I just posted it on the previous comment.

**Comment by gagansaini1212** [comment]
> > Replace with?
> 
> I just posted it on the previous comment.

I haven't found any post in the previous comment. Can you please provide with the design because there is one Beta Button for joining and I can't remove it without the design. It's better to provide complete details with the design.

**Comment by dimarconicola** [comment]
I have no idea what you're talking about. 
Anyway. Right now, when sharing the website, the image preview is the following:
<img width="536" alt="Screenshot 2019-04-02 at 16 42 46" src="https://user-images.githubusercontent.com/10923247/55463761-01174d00-55fa-11e9-8048-66fcc347f98d.png">

Instead, it should be this one
![preview picture dexpay](https://user-images.githubusercontent.com/10923247/55463785-0c6a7880-55fa-11e9-8e69-cfe422213086.png)

**Comment by perminder-klair** [comment]
@dimarconicola just tested preview on Discord and Twitter, it looks fine to me. Here are screenshots.

<img width="608" alt="Screenshot 2019-04-04 at 16 50 07" src="https://user-images.githubusercontent.com/3984412/55552041-e0362100-56f9-11e9-9e9e-3a9ed33ce607.png">
<img width="627" alt="Screenshot 2019-04-04 at 16 50 51" src="https://user-images.githubusercontent.com/3984412/55552042-e0ceb780-56f9-11e9-862c-878e2370dc32.png">

**Comment by dimarconicola** [comment]
Perfect. Thanks.
