### ISSUE TITLE
Reduce vertical padding

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-landing#4]
at the moment there's a bit too much top padding 

it would be better something like this

```
.section {
    padding: 0rem 1.5rem;
}

eyIwDb {
    position: relative;
    padding: 3.5rem 0rem;
}

.gZQYxG .logo {
    height: 118px;
    width: 175px;
}
```

**Comment by gagansaini1212** [comment]
padding-top in desktop view or mobile view?

**Comment by gagansaini1212** [comment]
Please check the PR. I made all those changes you mention above.

**Comment by perminder-klair** [comment]
PR merged, thanks @gagansaini1212
