### ISSUE TITLE
Add Discord Icon

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-landing#8]
Position: 1st

Link
https://discord.gg/QHBTnpt

Icon
![discordicon 2x](https://user-images.githubusercontent.com/10923247/53692834-e0f43400-3d96-11e9-9605-104988938860.png)

**Comment by gagansaini1212** [comment]
Added discord icon to the landing page.

**Comment by dimarconicola** [comment]
use @2x icon

<img width="170" alt="Screenshot 2019-03-12 at 13 01 39" src="https://user-images.githubusercontent.com/10923247/54198528-ff5cdc80-44c6-11e9-9dae-2f53a70490ef.png">

**Comment by gagansaini1212** [comment]
Can you please send me 2x Icon of discord.

**Comment by dimarconicola** [comment]
@gagansaini1212  Please use svg icon
[discord.svg.zip](https://github.com/dexlab-io/dexpay-landing/files/3000349/discord.svg.zip)
